openapi: 3.0.1
info:
  title: SLAAK Quiz
  description: Quiz CRUD API.
  version: 1.0.0
servers:
  - url: http://localhost:8082/api
paths:
  /user/{userName}/questions:
    get:
      summary: Get Questions
      operationId: getQuestions
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    post:
      summary: Post Questions
      operationId: postQuestions
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: save questions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostQuestion'
        required: true
      responses:
        200:
          description: Questions Added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    put:
      summary: Post Questions
      operationId: putQuestions
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: save questions
        content:
          application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        required: false
      responses:
        200:
          description: Questions Added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
      x-codegen-request-body-name: questions
components:
  schemas:
    PostQuestion:
      type: object
      properties:
        UserName:
          type: string
    Question:
      type: object
      properties:
        QuestionId:
          type: integer
          format: int64
        QuestionNum:
          type: integer
        Question:
          type: string
        Options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
    Option:
      type: object
      properties:
        Value:
          type: string
        Selected:
          type: boolean
          default: false
        Correct:
          type: boolean